kind: Service
apiVersion: v1
metadata:
  name: the-service
  annotations:
    service.cilium.io/global: "true"
spec:
  selector:
    deployment: hello
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8666
    targetPort: 8080
